describe('Saucedemo Test Add to Cart', () => {
    beforeEach(() => {
        cy.visit('')
        //cy.get('[data-test="username"]').type('standard_user')
        cy.ketik('[data-test="username"]', 'standard_user')
        //cy.get('[data-test="password"]').type('secret_sauce')
        cy.ketik('[data-test="password"]', 'secret_sauce')
        cy.get('[data-test="login-button"]').click()
        cy.get('.title').should('be.visible')
    })
    it('Success Add to Cart', () => {
        cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
        cy.get('.shopping_cart_link').should('have.text', '1')
        cy.get('.shopping_cart_link').click()
        cy.url().should('contain', '/cart.html')
        cy.get('.inventory_item_name')
        .should('contain.text', 'Sauce Labs Backpack')
        cy.get('[data-test="remove-sauce-labs-backpack"]').click()
        cy.get('.shopping_cart_link').should('have.text', '')
        cy.get('[data-test="continue-shopping"]').click()
        cy.url().should('contain', '/inventory.html')
        cy.viewport('ipad-mini')
        cy.wait(200)
        cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
        cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
        cy.get('.shopping_cart_link').should('have.text', '2')
        cy.get('.shopping_cart_link').click()
        cy.url().should('contain', '/cart.html')
        cy.get('#item_0_title_link > .inventory_item_name').should('be.visible')
        cy.get('#item_1_title_link > .inventory_item_name').should('be.visible')
    })
    
  })